#@ load ("@ytt:data", "data")
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: #@ data.values.name
  #@ if/end data.values.namespace:
  namespace: #@ data.values.namespace
spec:
  virtualhost:
    fqdn: #@ data.values.host 
    #@ if data.values.tls:
    tls:
      #@ if data.values.secret:
      secretName: #@ data.values.secret
      #@ else:
      secretName: #@ "{}-tls".format(data.values.host)
      #@ end
    #@ end
  tcpproxy:
    services:
    - name: #@ data.values.service.name
      port: #@ data.values.service.port
