#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")
#@ load("@ytt:data", "data")

---
apiVersion: v1
kind: Secret
metadata:
  name: clouddns-solver-credentials
  namespace: #@ data.values.namespace
data:
  service_account.json: #@ base64.encode(data.values.certmanager.solver.clouddns.keyfile)
#@ if data.values.staging:
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: #@ data.values.namespace
spec:
  acme:
   server: https://acme-staging-v02.api.letsencrypt.org/directory
   email: #@ json.decode(data.values.certmanager.solver.clouddns.keyfile)["client_email"]
   privateKeySecretRef:
     name: letsencrypt-credentials
   solvers:
   - dns01:
       clouddns:
         project: #@ json.decode(data.values.certmanager.solver.clouddns.keyfile)["project_id"]
         serviceAccountSecretRef:
           name: clouddns-solver-credentials
           key: service_account.json
#@ end
#@ if data.values.production:
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: #@ data.values.namespace
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: #@ json.decode(data.values.certmanager.solver.clouddns.keyfile)["client_email"]
    privateKeySecretRef:
      name: letsencrypt-n-credentials
    solvers:
    - dns01:
        clouddns:
          project: #@ json.decode(data.values.certmanager.solver.clouddns.keyfile)["project_id"]
          serviceAccountSecretRef:
            name: clouddns-solver-credentials
            key: service_account.json
#@ end